/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as layoutChatImport } from './routes/__layout-chat'
import { Route as layoutChatIndexImport } from './routes/__layout-chat/index'

// Create/Update Routes

const layoutChatRoute = layoutChatImport.update({
  id: '/__layout-chat',
  getParentRoute: () => rootRoute,
} as any)

const layoutChatIndexRoute = layoutChatIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => layoutChatRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__layout-chat': {
      id: '/__layout-chat'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof layoutChatImport
      parentRoute: typeof rootRoute
    }
    '/__layout-chat/': {
      id: '/__layout-chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof layoutChatIndexImport
      parentRoute: typeof layoutChatImport
    }
  }
}

// Create and export the route tree

interface layoutChatRouteChildren {
  layoutChatIndexRoute: typeof layoutChatIndexRoute
}

const layoutChatRouteChildren: layoutChatRouteChildren = {
  layoutChatIndexRoute: layoutChatIndexRoute,
}

const layoutChatRouteWithChildren = layoutChatRoute._addFileChildren(
  layoutChatRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof layoutChatRouteWithChildren
  '/': typeof layoutChatIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof layoutChatIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/__layout-chat': typeof layoutChatRouteWithChildren
  '/__layout-chat/': typeof layoutChatIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/__layout-chat' | '/__layout-chat/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  layoutChatRoute: typeof layoutChatRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  layoutChatRoute: layoutChatRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/__layout-chat"
      ]
    },
    "/__layout-chat": {
      "filePath": "__layout-chat.tsx",
      "children": [
        "/__layout-chat/"
      ]
    },
    "/__layout-chat/": {
      "filePath": "__layout-chat/index.tsx",
      "parent": "/__layout-chat"
    }
  }
}
ROUTE_MANIFEST_END */
